name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { NODE_ENV = "production" }

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[env.development]
vars = { NODE_ENV = "development" }

[[d1_databases]]
binding = "DB"
database_name = "status"
database_id = "d1f707e2-4bb3-4dbe-ad53-3dca961f9a90"

[vars]
JWT_SECRET = "your-secret-key-change-in-production" 
ENABLE_DB_INIT = "false" 
